---
kind: pipeline
type: docker
name: Kickoff
trigger:
  event:
    - push
    - pull_request
steps:
  - name: Notification Webhook
    image: appleboy/drone-discord
    settings:
      webhook_id:
        from_secret: discord_id
      webhook_token:
        from_secret: discord_token
      message: |-
        Drone CI multi-pipeline task initialized.
        Build number: {{build.number}}

---
kind: pipeline
type: exec
name: Basic testing
trigger:
  event:
    - push
    - pull_request
steps:
  - name: Terraform Plan
    commands:
      - mkdir -p ~/.ssh-temp
      - chmod 700 ~/.ssh-temp
      - ssh-keygen -t rsa -b 4096 -C "example@gmail.com" -N 'test' -f ~/.ssh-temp/id_rsa
      - gcloud auth activate-service-account --key-file /home/gruber/gcp.json
      - terraform init -reconfigure -force-copy
      - terraform plan
    when:
      event:
        - push
    environment:
      GOOGLE_APPLICATION_CREDENTIALS:
        from_secret: gcp_key_path
      PROJECT_ID:
        from_secret: gcp_project_id
      SERVICE_ACCOUNT:
        from_secret: gcp_app_key
      AWS_DEFAULT_REGION:
        from_secret: aws_region
      AWS_SECRET_ACCESS_KEY:
        from_secret: aws_key
      AWS_ACCESS_KEY_ID:
        from_secret: aws_id

  - name: Docker build
    commands:
      - task test-docker
    when:
      event:
        - push
    environment:
      GOOGLE_APPLICATION_CREDENTIALS:
        from_secret: gcp_key_path
      PROJECT_ID:
        from_secret: gcp_project_id
      SERVICE_ACCOUNT:
        from_secret: gcp_app_key
      AWS_DEFAULT_REGION:
        from_secret: aws_region
      AWS_SECRET_ACCESS_KEY:
        from_secret: aws_key
      AWS_ACCESS_KEY_ID:
        from_secret: aws_id

---
kind: pipeline
type: docker
name: Notification Basic Sucessfull
depends_on:
  - Basic testing
trigger:
  event:
    - push
    - pull_request
steps:
  - name: Notification Webhook
    image: appleboy/drone-discord
    settings:
      webhook_id:
        from_secret: discord_id
      webhook_token:
        from_secret: discord_token
      message: |-
        Drone CI multi-pipeline task initialized.
        Build number: {{build.number}}
      event:
        - push
    depends_on:
      - Docker build
      - Terraform Plan

---
kind: pipeline
type: docker
name: Notification Failure
trigger:
  status:
    - failure
  event:
    include:
      - push
      - pull_request
steps:
  - name: Notification Webhook
    image: appleboy/drone-discord
    settings:
      webhook_id:
        from_secret: discord_id
      webhook_token:
        from_secret: discord_token
      message: |-
        Drone CI pipeline {{build.number}} has failed.

  # - name: tfsec
  #   image: tfsec/tfsec
  #   commands:
  #     - tfsec . -e GCP003,AWS044,GEN003
  #   when:
  #     status:
  #       - success
  #       - failure
  #     event:
  #       - push
  #       - pull_request
  #   environment:
  #     GOOGLE_PROJECT:
  #       from_secret: gcp_project_id
  #     GOOGLE_KEY:
  #       from_secret: gcp_default
  #     AWS_DEFAULT_REGION:
  #       from_secret: aws_region
  #     AWS_SECRET_ACCESS_KEY:
  #       from_secret: awswwwwwwwwwwwwwwwwwwwwww_key
  #     AWS_ACCESS_KEY_ID:
  #       from_secret: aws_id

  # - name: terrascan
  #   image: accurics/terrascan
  #   commands:
  #     - terrascan scan
  #   when:
  #     status:
  #       - success
  #       - failure
  #     event:
  #       - push
  #       - pull_request
  #       - rollback
  #   environment:
  #     GOOGLE_PROJECT:
  #       from_secret: gcp_project_id
  #     GOOGLE_KEY:
  #       from_secret: gcp_default
  #     AWS_DEFAULT_REGION:
  #       from_secret: aws_region
  #     AWS_SECRET_ACCESS_KEY:
  #       from_secret: aws_key
  #     AWS_ACCESS_KEY_ID:
  #       from_secret: aws_id

---
kind: pipeline
type: docker
name: Amazon Web Services (AWS)
depends_on:
  - Basic testing
  - Kickoff
trigger:
  branch:
    - main
    - feature/aws_*
steps:
  - name: Setup AWS
    image: golang:1.16.4-alpine
    commands:
      - rm test/aws/go.mod || true
      - rm test/aws/go.sum || true
      - cd test/aws && go mod init "github.com/gruberdev/tf-free" && go mod tidy
    environment:
      AWS_DEFAULT_REGION:
        from_secret: aws_region
      AWS_SECRET_ACCESS_KEY:
        from_secret: aws_key
      AWS_ACCESS_KEY_ID:
        from_secret: aws_id

  - name: Unit Test EC2
    image: golang:1.16.4-alpine
    commands:
      - apk add build-base git curl
      - apk add --no-cache terraform --repository=http://dl-cdn.alpinelinux.org/alpine/edge/community
      - cd test/aws
      - go mod tidy
      - go test -v -timeout 14m -run TestUnitEC2
    depends_on:
      - Setup AWS
    environment:
      AWS_DEFAULT_REGION:
        from_secret: aws_region
      AWS_SECRET_ACCESS_KEY:
        from_secret: aws_key
      AWS_ACCESS_KEY_ID:
        from_secret: aws_id

---
kind: pipeline
type: docker
name: Google Cloud Provider (GCP)
depends_on:
  - Basic testing
  - Kickoff
trigger:
  branch:
    - main
    - feature/gcp_*
steps:
  - name: Setup
    image: golang:1.16.4-alpine
    commands:
      - cd test/gcp && go mod init "github.com/gruberdev/tf-free" && go mod tidy
      - cd ../docker && go mod init "github.com/gruberdev/tf-free" && go mod tidy
      - cd ../aws && go mod init "github.com/gruberdev/tf-free" && go mod tidy
    environment:
      GOOGLE_PROJECT:
        from_secret: gcp_project_id
      GOOGLE_KEY:
        from_secret: gcp_default
      AWS_DEFAULT_REGION:
        from_secret: aws_region
      AWS_SECRET_ACCESS_KEY:
        from_secret: aws_key
      AWS_ACCESS_KEY_ID:
        from_secret: aws_id

  - name: GCP Start Notification
    image: appleboy/drone-discord
    settings:
      webhook_id:
        from_secret: discord_id
      webhook_token:
        from_secret: discord_token
      message: |-
        Started GCP Pipeline on Drone CI.
        Build number: {{build.number}}

  - name: Unit Compute
    image: golang:1.16.5-alpine
    commands:
      - apk add build-base git curl
      - echo $GOOGLE_KEY > $PWD/gcp.json
      - apk add --no-cache terraform --repository=http://dl-cdn.alpinelinux.org/alpine/edge/community
      - export GOOGLE_APPLICATION_CREDENTIALS=$PWD/gcp.json
      - cd test/gcp
      - go mod tidy
      - go test -v -timeout 10m -run TestUnitCompute
    depends_on:
      - Setup
    environment:
      GOOGLE_PROJECT:
        from_secret: gcp_project_id
      GOOGLE_KEY:
        from_secret: gcp_default
      AWS_DEFAULT_REGION:
        from_secret: aws_region
      AWS_SECRET_ACCESS_KEY:
        from_secret: aws_key
      AWS_ACCESS_KEY_ID:
        from_secret: aws_id

  - name: Unit Networking
    image: golang:1.16.5-alpine
    commands:
      - apk add build-base git curl
      - echo $GOOGLE_KEY > $PWD/gcp.json
      - apk add --no-cache terraform --repository=http://dl-cdn.alpinelinux.org/alpine/edge/community
      - export GOOGLE_APPLICATION_CREDENTIALS=$PWD/gcp.json
      - cd test/gcp
      - go mod tidy
      - go test -v -timeout 10m -run TestUnitVPC
    depends_on:
      - Setup
    environment:
      GOOGLE_PROJECT:
        from_secret: gcp_project_id
      GOOGLE_KEY:
        from_secret: gcp_default
      AWS_DEFAULT_REGION:
        from_secret: aws_regions
      AWS_SECRET_ACCESS_KEY:
        from_secret: aws_key
      AWS_ACCESS_KEY_ID:
        from_secret: aws_id

  - name: Unit Bucket Storage
    image: golang:1.16.5-alpine
    commands:
      - apk add build-base git curl
      - echo $GOOGLE_KEY > $PWD/gcp.json
      - apk add --no-cache terraform --repository=http://dl-cdn.alpinelinux.org/alpine/edge/community
      - export GOOGLE_APPLICATION_CREDENTIALS=$PWD/gcp.json
      - cd test/gcp
      - go mod tidy
      - go test -v -timeout 8m -run  TestUnitStorage
    depends_on:
      - Setup
      - Unit Networking
      - Unit Compute
    environment:
      GOOGLE_PROJECT:
        from_secret: gcp_project_id
      GOOGLE_KEY:
        from_secret: gcp_default
      AWS_DEFAULT_REGION:
        from_secret: aws_region
      AWS_SECRET_ACCESS_KEY:
        from_secret: aws_key
      AWS_ACCESS_KEY_ID:
        from_secret: aws_id

  - name: Integration Core Provider
    image: golang:1.16.5-alpine
    commands:
      - apk add build-base git curl
      - echo $GOOGLE_KEY > $PWD/gcp.json
      - apk add --no-cache terraform --repository=http://dl-cdn.alpinelinux.org/alpine/edge/community
      - export GOOGLE_APPLICATION_CREDENTIALS=$PWD/gcp.json
      - cd test/gcp
      - go mod tidy
      - go test -v -timeout 10m -run TestIntegrationGCP
    depends_on:
      - Unit Networking
      - Unit Compute
      - Setup
      - Unit Storage
    environment:
      GOOGLE_PROJECT:
        from_secret: gcp_project_id
      GOOGLE_KEY:
        from_secret: gcp_default
      AWS_DEFAULT_REGION:
        from_secret: aws_region
      AWS_SECRET_ACCESS_KEY:
        from_secret: aws_key
      AWS_ACCESS_KEY_ID:
        from_secret: aws_id

  - name: Success @Testing GCP Module
    image: appleboy/drone-discord
    settings:
      webhook_id:
        from_secret: discord_id
      webhook_token:
        from_secret: discord_token
      message: |-
        **SUCCESSFULLY** finished building the GCP pipeline on Drone CI.
        Build number: {{build.number}}
    depends_on:
      - Unit Networking
      - Setup
      - Integration Core Provider
      - Unit Compute

---
kind: pipeline
type: docker
name: Documentation
depends_on:
  - Basic testing
  - Kickoff
trigger:
  branch:
    - main
  event:
    exclude:
      - pull_request
    include:
      - push
steps:
  - name: build_static
    image: node:14.4
    commands:
      - mkdir -p ~/.ssh
      - chmod 700 ~/.ssh
      - echo -e "Host *\n\tStrictHostKeyChecking no\n\tIdentityFile ~/ssh_key\n\n" > ~/.ssh/config
      - echo -e "$SSH_KEY" > ~/ssh_key
      - chmod 600 ~/ssh_key
      - apt-get update && apt-get install -y git openssh-server openssh-client
      - npm install -g @codedoc/cli
      - codedoc check
      - codedoc install
      - codedoc build
      - mkdir .public
      - cp -r docs/build/* .public
      - mv .public public
      - git config --global url.'https://${GITHUB_USER}:${GITHUB_PW}@github.com'.insteadOf 'https://github.com'
      - git clone $DOCS_REPO_URL
      - cp docs/vercel.json public/vercel.json
      - cp -r public/* $DOCS_REPO/ && cd $DOCS_REPO
      - git add . && git commit -a -m "updated docs" && git push
    environment:
      SSH_KEY:
        from_secret: ssh_id
      DOCS_REPO:
        from_secret: docs_dir_name
      DOCS_REPO_URL:
        from_secret: repository_url
      GITHUB_USER:
        from_secret: github_user
      GITHUB_PW:
        from_secret: github_token
