---
kind: pipeline
type: docker
name: tests
steps:
  - name: gcp single region test
    image: golang:1.16.4
    commands:
      - go mod tidy
      - cd test
      - go test -v TestSshAccessToComputeInstance
    when:
      event:
        - push
        - pull_request
        - rollback
