---
kind: pipeline
type: docker
name: Testing Google Cloud Provider (GCP)
steps:
  - name: unit_compute
    image: golang:1.16.4
    commands:
      - cd examples/gcp/unit/compute
      - rm gcp.json || true
      - echo $GCP_SERVICE_ACCOUNT > gcp.json
      - cd ../../../../
      - cd test
      - go mod init "github.com/gruberdev/tf-free"
      - go mod tidy
      - go test -v -timeout 5m -run TestUnitCompute
    when:
      event:
        - push
        - pull_request
        - rollback
    environment:
      GOOGLE_PROJECT:
        from_secret: gcp_project_id
      GCP_SERVICE_ACCOUNT:
        from_secret: gcp_project_key

  - name: unit_firewall
    image: golang:1.16.4
    commands:
      - cd examples/gcp/unit/firewall
      - rm gcp.json || true
      - echo $GCP_SERVICE_ACCOUNT > gcp.json
      - cd ../../../../
      - cd test
      - go mod init "github.com/gruberdev/tf-free"
      - go mod tidy
      - go test -v -timeout 5m -run TestUnitFirewall
    when:
      event:
        - push
        - pull_request
        - rollback
    environment:
      GOOGLE_PROJECT:
        from_secret: gcp_project_id
      GCP_SERVICE_ACCOUNT:
        from_secret: gcp_project_keyy

  - name: unit_vpc
    image: golang:1.16.4
    commands:
      - cd examples/gcp/unit/vpc
      - rm gcp.json || true
      - echo $GCP_SERVICE_ACCOUNT > gcp.json
      - cd ../../../../
      - cd test
      - go mod init "github.com/gruberdev/tf-free"
      - go mod tidy
      - go test -v -timeout 5m -run TestUnitVPC
    when:
      event:
        - push
        - pull_request
        - rollback
    environment:
      GOOGLE_PROJECT:
        from_secret: gcp_project_id
      GCP_SERVICE_ACCOUNT:
        from_secret: gcp_project_key

  - name: provider_integration
    image: golang:1.16.4
    commands:
      - cd examples/gcp/e2e
      - rm gcp.json || true
      - echo $GCP_SERVICE_ACCOUNT > gcp.json
      - cd ../../../../
      - cd test
      - go mod init "github.com/gruberdev/tf-free"
      - go mod tidy
      - go test -v -timeout 10m -run TestIntegrationGCP
    depends_on:
      - unit_compute
      - unit_firewall
      - unit_vpc
    when:
      event:
        - push
        - pull_request
        - rollback
    environment:
      GOOGLE_PROJECT:
        from_secret: gcp_project_id
      GCP_SERVICE_ACCOUNT:
        from_secret: gcp_project_key
