---
kind: pipeline
type: docker
name: Static Code Analysis
steps:
  - name: plan
    image: golang:1.16.4-alpine
    commands:
      - apk add build-base git curl
      - apk add --no-cache terraform --repository=http://dl-cdn.alpinelinux.org/alpine/edge/community
      - echo $GCP_SERVICE_ACCOUNT > gcp.json
      - export GOOGLE_APPLICATION_CREDENTIALS=$PWD/gcp.json
      - terraform init
      - terraform plan
    when:
      event:
        - push
        - pull_request
    environment:
      GOOGLE_PROJECT:
        from_secret: gcp_project_id
      GCP_SERVICE_ACCOUNT:
        from_secret: gcp_project_key

  - name: tfsec
    image: tfsec/tfsec
    commands:
      - tfsec . -e GCP003,AWS044,GEN003
    when:
      event:
        - push
        - pull_request
    environment:
      GOOGLE_PROJECT:
        from_secret: gcp_project_id

  - name: terrascan
    image: accurics/terrascan
    commands:
      - terrascan scan
    when:
      event:
        - push
        - pull_request
        - rollback
    environment:
      GOOGLE_PROJECT:
        from_secret: gcp_project_id

---
kind: pipeline
type: docker
name: Google Cloud Provider (GCP)
steps:
  - name: setup
    image: golang:1.16.4-alpine
    commands:
      - cd examples/gcp/unit/compute
      - echo $GCP_SERVICE_ACCOUNT > gcp.json
      - cd ../../../../
      - cd examples/gcp/unit/vpc
      - echo $GCP_SERVICE_ACCOUNT > gcp.json
      - cd ../../../../
      - cd examples/gcp/e2e
      - echo $GCP_SERVICE_ACCOUNT > gcp.json
      - cd ../../../
      - cd test
      - go mod init "github.com/gruberdev/tf-free"
      - go mod tidy
    when:
      branch:
        include:
          - master
          - feature/gcp_*
      event:
        - push
    environment:
      GOOGLE_PROJECT:
        from_secret: gcp_project_id
      GCP_SERVICE_ACCOUNT:
        from_secret: gcp_project_key

  - name: Unit Compute
    image: golang:1.16.4-alpine
    commands:
      - apk add build-base git curl
      - apk add --no-cache terraform --repository=http://dl-cdn.alpinelinux.org/alpine/edge/community
      - export GOOGLE_APPLICATION_CREDENTIALS=$PWD/examples/gcp/unit/compute/gcp.json
      - cd test
      - go mod tidy
      - go test -v -timeout 5m -run TestUnitCompute
    depends_on:
      - setup
    when:
      branch:
        include:
          - master
          - feature/gcp_*
      event:
        - push
    environment:
      GOOGLE_PROJECT:
        from_secret: gcp_project_id

  - name: Unit Networking
    image: golang:1.16.4-alpine
    commands:
      - apk add build-base git curl
      - apk add --no-cache terraform --repository=http://dl-cdn.alpinelinux.org/alpine/edge/community
      - export GOOGLE_APPLICATION_CREDENTIALS=$PWD/examples/gcp/unit/vpc/gcp.json
      - cd test
      - go mod tidy
      - go test -v -timeout 5m -run TestUnitVPC
    depends_on:
      - setup
    when:
      branch:
        include:
          - master
          - feature/gcp_*
      event:
        - push
    environment:
      GOOGLE_PROJECT:
        from_secret: gcp_project_id

  - name: Integration Core Provider
    image: golang:1.16.4-alpine
    commands:
      - apk add build-base git curl
      - apk add --no-cache terraform --repository=http://dl-cdn.alpinelinux.org/alpine/edge/community
      - export GOOGLE_APPLICATION_CREDENTIALS=$PWD/examples/gcp/e2e/gcp.json
      - cd test
      - go mod tidy
      - go test -v -timeout 10m -run TestIntegrationGCP
    when:
      branch:
        - master
      event:
        - push
    depends_on:
      - setup
      - Unit Networking
    environment:
      GOOGLE_PROJECT:
        from_secret: gcp_project_id

---
kind: pipeline
type: docker
name: Documentation
steps:
  - name: build_static
    image: node:14.4
    commands:
      - mkdir -p ~/.ssh
      - chmod 700 ~/.ssh
      - echo -e "Host *\n\tStrictHostKeyChecking no\n\tIdentityFile ~/ssh_key\n\n" > ~/.ssh/config
      - echo -e "$SSH_KEY" > ~/ssh_key
      - chmod 600 ~/ssh_key
      - apt-get update && apt-get install -y git openssh-server openssh-client
      - npm install -g @codedoc/cli
      - codedoc check
      - codedoc install
      - codedoc build
      - mkdir .public
      - cp -r docs/build/* .public
      - mv .public public
      - git config --global url.'https://${GITHUB_USER}:${GITHUB_PW}@github.com'.insteadOf 'https://github.com'
      - git clone $DOCS_REPO_URL
      - cp -r public/* $DOCS_REPO/ && cd $DOCS_REPO
      - git add . && git commit -a -m "updated docs" && git push
    when:
      branch:
        - master
        - docs
      event:
        - push
    environment:
      SSH_KEY:
        from_secret: ssh_id
      DOCS_REPO:
        from_secret: docs_dir_name
      DOCS_REPO_URL:
        from_secret: repository_url
      GITHUB_USER:
        from_secret: github_user
      GITHUB_PW:
        from_secret: github_token
