---
kind: pipeline
type: docker
name: tests
steps:
  - name: testing GCP provider E2E
    image: golang:1.16.4
    commands:
      - cd examples/gcp/e2e
      - rm gcp.json || true
      - echo $GCP_SERVICE_ACCOUNT > gcp.json
      - cd ../../../
      - cd test
      - go mod init "github.com/gruberdev/tf-free"
      - go mod tidy
      - go test -v -run EndtoEndGCP
    when:
      event:
        - push
        - pull_request
        - rollback
    environment:
      TF_VAR_gcp_project_id:
        from_secret: gcp_project_id
      GCP_SERVICE_ACCOUNT:
        from_secret: gcp_project_key
