---
kind: pipeline
type: docker
name: tests
steps:
  - name: gcp simple unit test
    image: golang:1.16.4
    commands:
      - (rm gcp.json || true ) && echo $GCP_SERVICE_ACCOUNT > gcp.json
      - cd test
      - export GOPATH=$(pwd)
      - export PATH=$PATH:$GOPATH/bin
      - go mod init "github.com/gruberdev/tf-free"
      - go mod tidy
      - go test -v TestTerraformGcpHelloWorldExample
    when:
      event:
        - push
        - pull_request
        - rollback
    environment:
      TF_VAR_gcp_project_id:
        from_secret: gcp_project_id
      GCP_SERVICE_ACCOUNT:
        from_secret: gcp_project_key
