image: node:14.4
pages:
  stage: deploy
  script:
    - npm install -g @codedoc/cli
    - codedoc check
    - codedoc install
    - codedoc build
    - mkdir .public
    - cp -r * .public
    - mv .public public
  artifacts:
    paths:
      - public
