version: "3"

tasks:
  default:
    cmds:
      - task: clean
      - task: tf-clean
      - task: generate
      - task: vet
      - task: fmt
      - task: lint
      - task: test
      - task: mod

  docker-init:
    desc: Create and cache your Docker container
    cmds:
      - docker volume rm cache_terraform || true
      - docker volume rm repository_results || true
      - docker volume create cache_terraform || true
      - docker volume create repository_results || true

  docker:
    desc: Create and cache your Docker container
    deps:
      - build
    cmds:
      - docker run -it --rm --name terraformfree -e GOOGLE_PROJECT=$GOOGLE_PROJECT -e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID -e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY -e AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION terraformfree:latest

  build:
    desc: Create and cache your Docker container
    cmds:
      - docker stop terraformfree:latest || true
      - docker rm terraformfree:latest || true
      - docker build --cache-from terraformfree:latest --no-cache -t terraformfree:latest .

  build-all:
    desc: Build executable binary with GoReleaser.
    cmds:
      - goreleaser --snapshot --skip-publish --rm-dist

  generate:
    desc: Initialize test fakes
    cmds:
      - go generate ./...

  vet:
    desc: Initialize module and build cache, and remake go.sum file.
    cmds:
      - go vet ./...

  gcp:
    desc: Initialize module and build cache, and remake go.sum file.
    cmds:
      - gcloud auth application-default login

  fmt:
    desc: Format Go files
    cmds:
      - go fmt ./...

  mod:
    desc: Initialize module and build cache, and remake go.sum file on root directory.
    cmds:
      - go mod tidy
      - cd tools && go mod tidy

  docs-gen:
    desc: Build documentation using Terraform-docs and the task command
    cmds:
      - terraform-docs markdown -c .terraform-docs.yml . --output-file README.md
      - terraform-docs markdown -c .terraform-docs.yml ./modules/aws --output-file README.md --header-from "header.md"
      - terraform-docs markdown -c .terraform-docs.yml ./modules/aws/ec2 --output-file README.md
      - terraform-docs markdown -c .terraform-docs.yml ./modules/aws/rds  --output-file README.md
      - terraform-docs markdown -c .terraform-docs.yml ./modules/gcp  --output-file README.md
      - terraform-docs markdown -c .terraform-docs.yml ./modules/gcp/compute --output-file README.md
      - terraform-docs markdown -c .terraform-docs.yml ./modules/gcp/firewall --output-file README.md
      - terraform-docs markdown -c .terraform-docs.yml ./modules/gcp/vpc --output-file README.md
      - terraform-docs markdown -c .terraform-docs.yml ./modules/gcp/storage --output-file README.md

  docs:
    desc: Initialize module and build cache, and remake go.sum file on root directory.
    cmds:
      - cd docs && docker-compose down || true
      - cd docs && docker build -t tf-free:docs .
      - cd docs && docker-compose up --build -d

  test:
    desc: Test and print out code coverage as html.
    cmds:
      - go test -race -covermode=atomic -coverprofile=coverage.out ./...
      - go tool cover -html=coverage.out -o coverage.html

  lint:
    desc: Linter built on Docker.
    cmds:
      - go mod verify
      - docker run --rm -v $(pwd):/app -w /app golangci/golangci-lint:v1.40.1 golangci-lint run --enable gosec --timeout 3m0s ./...
    sources:
      - ./go.mod
      - "**/*.go"

  go-clean:
    desc: Clean cache on root module.
    cmds:
      - rm -f ./go.sum
      - go clean -cache || true
      - go clean -modcache || true

  graph:
    desc: Create beautiful Terraform Graphs
    cmds:
      - go get github.com/pcasteran/terraform-graph-beautifier
      - terraform graph | terraform-graph-beautifier --exclude="module.root.provider" --output-type=cyto-html > graph.html

  gcp-init:
    desc: Bootstrapping Google Cloud provider testing files
    cmds:
      - cd test/gcp && rm go.mod || true
      - cd test/gcp && rm go.sum || true
      - cd test/gcp && go mod init "github.com/gruberdev/tf-free" && go mod tidy

  gcp-test:
    desc: Terraform testing (GCP provider)
    deps:
      - gcp-init
      - unit-network-gcp
      - unit-compute-gcp
      - unit-storage-gcp
    cmds:
      - cd test/gcp && go test -v -timeout 10m -run TestIntegrationGCP

  aws-init:
    desc: Bootstrapping AWS provider testing files
    cmds:
      - cd test/aws && rm go.mod || true
      - cd test/aws && rm go.sum || true
      - cd test/aws && go mod init "github.com/gruberdev/tf-free" && go mod tidy

  aws-test:
    deps:
      - aws-init
    desc: Terraform testing (AWS provider)
    cmds:
      - cd test/aws && go mod init "github.com/gruberdev/tf-free" && go mod tidy
      - cd test/aws && go test -v -timeout 10m -run TestUnitEC2
      - cd test/aws && go test -v -timeout 10m -run TestUnitRDS

  full-test-local:
    desc: Terraform testing all providers.
    deps:
      - gcp-test
      - aws-test
      - docker-test
    cmds:
      - echo "Finished testing."

  apply-local:
    desc: Terraform standard local apply command
    cmds:
      - terraform init
      - terraform apply -auto-approve

  destroy-local:
    desc: Terraform standard local destroy command
    cmds:
      - terraform destroy -auto-approve

  init:
    desc: Terraform standard local init command
    cmds:
      - terraform init -upgrade

  initialapply:
    desc: Terraform standard initial apply command (w/ Backend)
    cmds:
      - terraform init -reconfigure
      - terraform apply -auto-approve
      - terraform init -force-copy

  init-docker:
    cmds:
      - cd test/docker && rm go.mod || true
      - cd test/docker && rm go.sum || true
      - cd test/docker && go mod init "github.com/gruberdev/tf-free" && go mod tidy

  docker-test:
    desc: Terraform standard initialization
    deps:
      - init-docker
    cmds:
      - cd test/docker && go test -v -timeout 45m -run TestDockerBuild

  lastdestroy:
    desc: Terraform standard initialization
    cmds:
      - terraform apply -var backend_destroy=true -target module.terraform_state_backend -auto-approve
      - terraform init -force-copy
      - terraform destroy -target  module.aws.module.rds.aws_db_instance.rds -auto-approve
      - terraform destroy -auto-approve

  dbdestroy:
    desc: Terraform standard initialization
    cmds:
      - terraform destroy -target module.aws.module.rds.aws_db_instance.rds -auto-approve

  apply-aws:
    desc: Terraform standard initialization
    cmds:
      - cd modules/aws && terraform apply -auto-approve

  apply-gcp:
    desc: Terraform standard initialization
    cmds:
      - cd modules/gcp && terraform apply -auto-approve

  destroy-gcp:
    desc: Terraform standard initialization
    cmds:
      - cd modules/gcp && terraform destroy -auto-approve

  dockerlint:
    desc: Terraform standard initialization
    cmds:
      - docker run --rm -i hadolint/hadolint < Dockerfile || true

  backend-enable:
    desc: How to transfer the backend to S3 (Remote)
    cmds:
      - terraform init -force-copy

  backend-disable:
    desc: How to destroy the backend stored in S3
    cmds:
      - terraform apply -target module.terraform_state_backend -auto-approve
      - terraform init -force-copy

  destroy-aws:
    desc: Terraform standard initialization
    cmds:
      - cd modules/aws && terraform destroy -auto-approve

  restart-aws:
    desc: Terraform standard initialization
    cmds:
      - cd modules/aws && terraform destroy -auto-approve
      - cd modules/aws && terraform apply -auto-approve

  tf-clean:
    desc: Terraform standard initialization
    cmds:
      - rm -rf ./.terraform || true
      - rm terraform.tfstate || true
      - rm terraform.tfstate.backup || true
      - rm ./.terraform.lock.hcl || true
      - rm backend.tf || true
      - rm errored.tfstate || true
      - rm graph.html || true
      - rm index.html || true
      - cd modules && cd gcp && rm -rf ./.terraform && rm ./.terraform.lock.hcl || true
      - cd modules && cd gcp && cd vpc && rm -rf ./.terraform && rm ./.terraform.lock.hcl || true
      - cd modules && cd gcp && cd firewall && rm -rf ./.terraform && rm ./.terraform.lock.hcl || true
      - cd modules && cd gcp && cd compute && rm -rf ./.terraform && rm ./.terraform.lock.hcl || true
      - cd modules && cd aws && rm -rf ./.terraform && rm ./.terraform.lock.hcl || true
      - cd modules && cd aws && cd ec2 && rm -rf ./.terraform && rm ./.terraform.lock.hcl || true
      - cd modules && cd aws && cd rds && rm -rf ./.terraform && rm ./.terraform.lock.hcl || true

  init-drone:
    desc: Terraform standard initialization
    cmds:
      - apk add build-base git curl
      - apk add --no-cache terraform --repository=http://dl-cdn.alpinelinux.org/alpine/edge/community

  unit-compute-gcp:
    deps:
      - gcp-init
    cmds:
      - cd test/gcp && go test -v -timeout 5m -run TestUnitCompute

  unit-storage-gcp:
    deps:
      - gcp-init
    cmds:
      - cd test/gcp && go test -v -timeout 5m -run TestUnitStorage

  unit-network-gcp:
    deps:
      - gcp-init
    cmds:
      - cd test/gcp && go test -v -timeout 5m -run TestUnitVPC

  unit-ec2-aws:
    deps:
      - aws-init
    cmds:
      - cd test/aws && go test -v -timeout 15m -run TestUnitEC2

  unit-rds-aws:
    deps:
      - aws-init
    cmds:
      - cd test/aws && go test -v -timeout 30m -run TestUnitRDS

  blast-radius:
    cmds:
      - docker run --rm -it -p 5013:5000 -v $(pwd):/data:ro -v $(pwd)/blast:/tmp/results --security-opt apparmor:unconfined --cap-add=SYS_ADMIN blastradius:local
