version: '3'
vars:
  PATH_ERROR: is not installed or correctly configured in PATH.

silent: true

tasks:
  aws:
    env:
      AWS_DEFAULT_REGION: "us-east-1"
    preconditions:
      - sh: 'which awsweeper'
        msg: 'kustomize {{.PATH_ERROR}}'
    cmds:
      - awsweeper config/aws-filter.yaml
    silent: true

  gcp:
    preconditions:
      - sh: 'which gcloud'
        msg: 'kustomize {{.PATH_ERROR}}'
    cmds:
      - docker run --rm --name cloudblaster -w /config -v ./config:/config docker.io/grubertech/cloudblaster:0.1
    silent: true
