version: "3.8"
services:
  docs:
    build: .
    ports:
      - 3000:3000
    # Volume root folder on `/home/blog`,
    # but exclude `/home/blog/.codedoc/node_modules" (since the container env should install its own modules).
    #
    volumes:
      - "..:/home/docs"
      - "/home/docs/.codedoc/node_modules/"
